# .streamlit/secrets.toml

[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "test"
username = "root"
password = "taha"

[connections.databaseprojphase2_db]
url = "sqlite:///databaseprojphase2.db"